name: active_grid_core
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  intl: ^0.16.1
  http: ^0.12.2
  provider: ^4.3.2+2
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^4.1.3
  json_schema: ^2.2.1
  flutter_test:
    sdk: flutter

flutter:
