include: package:pedantic/analysis_options.yaml

analyzer:
  exclude:
    - '**/example/lib/*.dart'

linter:
  rules:
    rules:
      public_member_api_docs: true
      sort_constructors_first: true
      hash_and_equals: true