include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**/grid_row_dropdown.dart'
    - '**/apptive_grid_icons_icons.dart'

linter:
  rules:
    public_member_api_docs: false
    sort_constructors_first: true
    hash_and_equals: true
    avoid_print: true
    require_trailing_commas: true
    always_use_package_imports: true