include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**/example/lib/*.dart'
    - '**/grid_row_dropdown.dart'

linter:
  rules:
    public_member_api_docs: true
    sort_constructors_first: true
    hash_and_equals: true
    avoid_print: true
    require_trailing_commas: true