/// Flutter icons ApptiveGridIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ApptiveGridIcons
///      fonts:
///       - asset: fonts/ApptiveGridIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class ApptiveGridIcons {
  ApptiveGridIcons._();

  static const _kFontFam = 'ApptiveGridIcons';
  static const String? _kFontPkg = null;

  static const IconData more =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grid =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData form =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
