name: apptive_grid_web_apptive
description: A Flutter Package to enable Flutter Apptives on ApptiveGrid Web Client
version: 0.4.0
homepage: https://apptivegrid.de
repository: https://github.com/ApptiveGrid/apptive_grid_flutter/tree/main/packages/apptive_grid_web_apptive
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  apptive_grid_core: ^2.1.0
  collection: ^1.17.1
  flutter:
    sdk: flutter

dev_dependencies:
  mocktail: ^1.0.1
  flutter_test:
    sdk: flutter

flutter:
