name: apptive_grid_user_management
description: Package to add UserManagement through ApptiveGrid to a Flutter App. This provides Login/Register Widgets and options to confirm accounts
version: 2.0.3
homepage: https://www.apptivegrid.de
repository: https://github.com/ApptiveGrid/apptive_grid_flutter/tree/main/packages/apptive_grid_user_management

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  apptive_grid_core: ^2.1.1
  flutter:
    sdk: flutter
  http: '>=0.13.6 <2.0.0'
  intl: ^0.19.0
  password_rule_check: ^0.2.1
  uni_links: ^0.5.1

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.1
  plugin_platform_interface: ^2.1.4
  uni_links_platform_interface: ^1.0.0


flutter:

