name: apptive_grid_user_management
description: Package to add UserManagement through ApptiveGrid to a Flutter App. This provides Login/Register Widgets and options to confirm accoutns
version: 0.0.1-alpha.1
homepage: https://www.apptivegrid.de

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  apptive_grid_core: ^0.8.0-alpha.9
  flutter:
    sdk: flutter
  http: ^0.13.4
  intl: ^0.17.0
  password_rule_check: ^0.1.0
  uni_links: ^0.5.1

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  plugin_platform_interface: ^2.1.2
  uni_links_platform_interface: ^1.0.0


flutter:

