name: active_grid_grid_builder
description: A Flutter Package to build Widgets based on Data from an ActiveGrid Grid.
version: 0.1.1
homepage: https://www.activegrid.de

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  active_grid_core: ^0.1.1
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.11.0
  mocktail: ^0.1.1
  flutter_test:
    sdk: flutter


flutter:

