name: apptive_grid_grid_builder
description: A Flutter Package to build Widgets based on Data from an ApptiveGrid Grid.
version: 0.8.0-alpha.3
homepage: https://www.apptivegrid.de

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  apptive_grid_core: ^0.8.0-alpha.5
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.11.1
  mocktail: ^0.2.0
  flutter_test:
    sdk: flutter


flutter:

