name: apptive_grid_grid_builder
description: A Flutter Package to build Widgets based on Data from an ApptiveGrid Grid.
version: 2.0.1
homepage: https://www.apptivegrid.de
repository: https://github.com/ApptiveGrid/apptive_grid_flutter/tree/main/packages/apptive_grid_grid_builder

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  apptive_grid_core: ^2.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.11.1
  mocktail: ^1.0.1
  flutter_test:
    sdk: flutter


flutter:

