name: apptive_grid_grid_builder
description: A Flutter Package to build Widgets based on Data from an ApptiveGrid Grid.
version: 1.2.0
homepage: https://www.apptivegrid.de
repository: https://github.com/ApptiveGrid/apptive_grid_flutter/tree/main/packages/apptive_grid_grid_builder

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  apptive_grid_core: ^1.4.0
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.11.1
  mocktail: ^0.3.0
  flutter_test:
    sdk: flutter


flutter:

