name: active_grid_core
description: Core Library for ActiveGrid used to provide general ActiveGrid functionality to other Packages or Apps
version: 0.0.1
homepage: https://zweidenker.de

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  intl: ^0.17.0
  http: ^0.13.1
  provider: ^5.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  mocktail: ^0.1.1
  json_schema2: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
