name: apptive_grid_core
description: Core Library for ApptiveGrid used to provide general ApptiveGrid functionality to other Packages or Apps
version: 0.14.5
homepage: https://www.apptivegrid.de
repository: https://github.com/ApptiveGrid/apptive_grid_flutter/tree/main/packages/apptive_grid_core

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.16.0
  image: ^3.2.2
  intl: ^0.17.0
  http: ^0.13.5
  mime: ^1.0.2
  provider: ^6.0.4
  openid_client: ^0.4.6
  uni_links: ^0.5.1
  universal_file: ^1.0.0
  universal_platform: ^1.0.0+1
  url_launcher: ^6.1.7
  uuid: ^3.0.7
  flutter_secure_storage: ^6.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1
  pedantic: ^1.11.1
  mocktail: ^0.3.0
  url_launcher_platform_interface: ^2.1.1
  uni_links_platform_interface: ^1.0.0
  plugin_platform_interface: ^2.1.3
  flutter_secure_storage_platform_interface: ^1.0.1
  flutter_test:
    sdk: flutter

flutter:
