name: apptive_grid_core
description: Core Library for ApptiveGrid used to provide general ApptiveGrid functionality to other Packages or Apps
version: 1.8.1
homepage: https://www.apptivegrid.de
repository: https://github.com/ApptiveGrid/apptive_grid_flutter/tree/main/packages/apptive_grid_core

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.17.2
  image: ^4.0.17
  intl: ^0.18.0
  http: '>=0.13.6 <2.0.0'
  mime: ^1.0.4
  provider: ^6.0.5
  openid_client: ^0.4.7
  uni_links: ^0.5.1
  universal_file: ^1.0.0
  universal_platform: ^1.0.0+1
  url_launcher: ^6.1.10
  uuid: ^4.1.0
  flutter_secure_storage: ^9.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1
  pedantic: ^1.11.1
  mocktail: ^1.0.1
  url_launcher_platform_interface: ^2.1.2
  uni_links_platform_interface: ^1.0.0
  plugin_platform_interface: ^2.1.4
  flutter_secure_storage_platform_interface: ^1.0.1
  flutter_test:
    sdk: flutter

flutter:
