name: apptive_grid_core
description: Core Library for ApptiveGrid used to provide general ApptiveGrid functionality to other Packages or Apps
version: 0.9.4
homepage: https://www.apptivegrid.de
repository: https://github.com/ApptiveGrid/apptive_grid_flutter/tree/main/packages/apptive_grid_core

environment:
  sdk: '>=2.16.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  image: ^3.1.3
  intl: ^0.17.0
  http: ^0.13.4
  mime: ^1.0.1
  provider: ^6.0.2
  openid_client: ^0.4.3
  uni_links: ^0.5.1
  url_launcher: ^6.0.17
  uuid: ^3.0.6
  flutter_secure_storage: ^5.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.4
  pedantic: ^1.11.1
  mocktail: ^0.2.0
  url_launcher_platform_interface: ^2.0.4
  uni_links_platform_interface: ^1.0.0
  plugin_platform_interface: ^2.0.2
  flutter_secure_storage_platform_interface: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
