name: apptive_grid_extension
description: A Flutter Package to create ApptiveGrid Extensions
version: 0.0.1
homepage: https://apptivegrid.de
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  apptive_grid_core: ^0.2.6+1
  flutter:
    sdk: flutter

dev_dependencies:
  mocktail: ^0.1.1
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
