name: active_grid_form
description: A Flutter Package to display ActiveGrid Forms inside a Flutter App.
version: 0.0.1
homepage: https://zweidenker.de

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  lottie: ^0.7.0+1
  flutter:
    sdk: flutter

  active_grid_core:
    path: ../active_grid_core # TODO: Use hosted version on pub.dev once published

dev_dependencies:
  pedantic: ^1.9.2
  mockito: ^4.1.3
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
