name: active_grid_form
description: A Flutter Package to display ActiveGrid Forms inside a Flutter App.
version: 0.1.0
homepage: https://www.activegrid.de

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  lottie: ^1.0.1
  flutter:
    sdk: flutter

  active_grid_core:
    path: ../active_grid_core # TODO: Use hosted version on pub.dev once published

dev_dependencies:
  pedantic: ^1.11.0
  mocktail: ^0.1.1
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
