name: apptive_grid_form
description: A Flutter Package to display ApptiveGrid Forms inside a Flutter App.
version: 0.15.0
homepage: https://www.apptivegrid.de
repository: https://github.com/ApptiveGrid/apptive_grid_flutter/tree/main/packages/apptive_grid_form

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  apptive_grid_core: ^1.0.0
  file_picker: ^5.2.2
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6
  flutter_typeahead: ^4.1.1
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.1
  google_maps_flutter_platform_interface: ^2.2.4
  hand_signature: ^2.3.0+1
  http: ^0.13.5
  image_picker: ^0.8.6
  intl: ^0.17.0
  linked_scroll_controller: ^0.2.0
  lottie: ^2.0.0
  permission_handler: ^10.2.0
  permission_handler_platform_interface: ^3.9.0
  provider: ^6.0.4
  universal_file: ^1.0.0
  universal_platform: ^1.0.0+1

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_localizations:
    sdk: flutter
  image_picker_platform_interface: ^2.6.2
  pedantic: ^1.11.1
  mocktail: ^0.3.0
  mocktail_image_network: ^0.3.1
  plugin_platform_interface: ^2.1.3
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
