name: apptive_grid_form
description: A Flutter Package to display ApptiveGrid Forms inside a Flutter App.
version: 0.9.0-alpha.3
homepage: https://www.apptivegrid.de

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  apptive_grid_core: ^0.8.0-alpha.1
  file_picker: ^4.2.0
  flutter:
    sdk: flutter
  intl: ^0.17.0
  linked_scroll_controller: ^0.2.0
  lottie: ^1.2.1
  mime: ^1.0.1
  provider: ^6.0.1

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_localizations:
    sdk: flutter
  pedantic: ^1.11.1
  mocktail: ^0.2.0
  http: ^0.13.4
  plugin_platform_interface: ^2.0.2
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
