name: apptive_grid_form
description: A Flutter Package to display ApptiveGrid Forms inside a Flutter App.
version: 0.10.0-alpha.6
homepage: https://www.apptivegrid.de
repository: https://github.com/ApptiveGrid/apptive_grid_flutter/tree/main/packages/apptive_grid_form

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  apptive_grid_core: ^0.10.0-alpha.6
  file_picker: ^4.6.0
  flutter:
    sdk: flutter
  flutter_typeahead: ^4.0.0
  geolocator: ^8.2.1
  google_maps_flutter: ^2.1.6
  google_maps_flutter_platform_interface: ^2.1.7
  google_maps_webservice: ^0.0.20-nullsafety.5
  http: ^0.13.4
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  linked_scroll_controller: ^0.2.0
  lottie: ^1.3.0
  permission_handler: ^9.2.0
  permission_handler_platform_interface: ^3.7.0
  provider: ^6.0.3
  universal_platform: ^1.0.0+1

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_localizations:
    sdk: flutter
  image_picker_platform_interface: ^2.5.0
  pedantic: ^1.11.1
  mocktail: ^0.3.0
  plugin_platform_interface: ^2.1.2
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
