name: apptive_grid_form
description: A Flutter Package to display ApptiveGrid Forms inside a Flutter App.
version: 2.1.1
homepage: https://www.apptivegrid.de
repository: https://github.com/ApptiveGrid/apptive_grid_flutter/tree/main/packages/apptive_grid_form

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  apptive_grid_core: ^2.1.1
  collection: ^1.17.2
  file_picker: ^5.2.11
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10
  flutter_typeahead: ^4.3.8
  geolocator: ^10.0.1
  google_maps_flutter: ^2.9.0
  google_maps_flutter_platform_interface: ^2.9.0
  hand_signature: ^3.0.1
  http: '>=0.13.6 <2.0.0'
  image_picker: ^1.0.4
  intl: ^0.19.0
  linked_scroll_controller: ^0.2.0
  lottie: ^2.3.2
  permission_handler: ^11.0.1
  permission_handler_platform_interface: ^3.9.0
  provider: ^6.0.5
  universal_file: ^1.0.0
  universal_platform: ^1.0.0+1

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_localizations:
    sdk: flutter
  image_picker_platform_interface: ^2.6.3
  pedantic: ^1.11.1
  mocktail: ^1.0.3
  mocktail_image_network: ^1.1.0
  plugin_platform_interface: ^2.1.4
  flutter_test:
    sdk: flutter
  golden_toolkit:

flutter:
  assets:
    - assets/
