name: apptive_grid_form
description: A Flutter Package to display ApptiveGrid Forms inside a Flutter App.
version: 0.7.3
homepage: https://www.apptivegrid.de

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  intl: ^0.17.0
  linked_scroll_controller: ^0.2.0
  lottie: ^1.2.1
  flutter:
    sdk: flutter

  apptive_grid_core: ^0.6.0+1

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_localizations:
    sdk: flutter
  pedantic: ^1.11.1
  mocktail: ^0.2.0
  http: ^0.13.4
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
