name: apptive_grid_form
description: A Flutter Package to display ApptiveGrid Forms inside a Flutter App.
version: 0.10.0-alpha.6
homepage: https://www.apptivegrid.de
repository: https://github.com/ApptiveGrid/apptive_grid_flutter/tree/main/packages/apptive_grid_form

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  apptive_grid_core: ^0.10.0-alpha.5
  file_picker: ^4.3.0
  flutter:
    sdk: flutter
  flutter_typeahead: ^3.2.4
  geolocator: ^8.0.1
  google_maps_flutter: ^2.1.1
  google_maps_flutter_platform_interface: ^2.1.3
  http: ^0.13.4
  image_picker: ^0.8.4+4
  intl: ^0.17.0
  linked_scroll_controller: ^0.2.0
  lottie: ^1.2.1
  permission_handler: ^8.3.0
  permission_handler_platform_interface: ^3.7.0
  provider: ^6.0.2
  universal_platform: ^1.0.0+1

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_localizations:
    sdk: flutter
  image_picker_platform_interface: ^2.4.1
  pedantic: ^1.11.1
  mocktail: ^0.2.0
  plugin_platform_interface: ^2.0.2
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
