name: apptive_grid_grid_builder_example
description: A example on how to use the ApptiveGridGridBuilder Package.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

  apptive_grid_grid_builder:
    path: ../

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
