name: apptive_grid_theme
description: All theming for apps using ApptiveGrid. This includes colors, icons and fonts used by ApptiveGrid.
version: 0.1.2
homepage: https://www.apptivegrid.de
repository: https://github.com/ApptiveGrid/apptive_grid_flutter/tree/main/packages/apptive_grid_theme

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  universal_platform: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  golden_toolkit: ^0.13.0

flutter:
  generate: true
  uses-material-design: true

  fonts:
    - family: DMSans
      fonts:
        - asset: fonts/DMSans-Medium.ttf
          weight: 400
        - asset: fonts/DMSans-Bold.ttf
          weight: 700
        - asset: fonts/DMSans-Regular.ttf
          weight: 400
    - family: ApptiveGridIcons
      fonts:
        - asset: fonts/ApptiveGridIcons.ttf
