name: apptive_grid_theme
description: All theming for apps using ApptiveGrid. This includes colors, icons and fonts used by ApptiveGrid.
version: 1.3.0
homepage: https://www.apptivegrid.de
repository: https://github.com/ApptiveGrid/apptive_grid_flutter/tree/main/packages/apptive_grid_theme

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  material_design_icons_flutter: ^7.0.7296
  universal_platform: ^1.0.0+1


dev_dependencies:
  alchemist:
    git:
      url: https://github.com/abausg/alchemist
      ref: flutter-3-13
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  golden_toolkit: ^0.15.0

flutter:
  generate: true
  uses-material-design: true

  fonts:
    - family: DMSans
      fonts:
        - asset: fonts/DMSans-Medium.ttf
          weight: 400
        - asset: fonts/DMSans-Bold.ttf
          weight: 700
        - asset: fonts/DMSans-Regular.ttf
          weight: 400
