name: Build

on:
  push:
    branches:
      - main
  pull_request:


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality:
    name: Quality Checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
      - uses: bluefireteam/melos-action@v1

      - name: Format, Lint, Publishability
        run: melos run lint:all
      - name: Run Tests
        run: melos run test:all_coverage
      - name: Core Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1
        with:
          path: ./packages/apptive_grid_core/coverage/lcov.info
          min_coverage: 99.2
      - name: Form Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1
        with:
          path: ./packages/apptive_grid_form/coverage/lcov.info
      - name: Grid Builder Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1
        with:
          path: ./packages/apptive_grid_grid_builder/coverage/lcov.info
      - name: User Management Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1
        with:
          path: ./packages/apptive_grid_user_management/coverage/lcov.info

  android_examples:
    name: Build Android Examples
    needs: quality
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
      - uses: bluefireteam/melos-action@v1

      - name: Build Android Examples
        run: melos run build:android

  ios_examples:
    name: Build iOS Examples
    needs: quality
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
      - uses: bluefireteam/melos-action@v1

      - name: Build iOS Examples
        run: melos run build:ios

  report:
    name: Report to Slack
    needs: [
      quality,
      android_examples,
      ios_examples
    ]
    if: ${{ always() && !cancelled() && github.ref_name == 'main'}}
    runs-on: ubuntu-latest

    steps:
      - uses: martialonline/workflow-status@v3
        id: check
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: 'ApptiveGrid Flutter Packages'
          SLACK_ICON: "https://apptiveattachmentsprod-apptiveattachmentbucket-1g9k6859i00z1.s3.eu-central-1.amazonaws.com/8398ca4c-c339-4c3e-89c2-8d0495e4b868"
          SLACK_COLOR: ${{ steps.check.outputs.status }}
          SLACK_FOOTER: ''