name: Build

on:
  pull_request:


jobs:
  quality:
    name: Quality Checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
      - uses: bluefireteam/melos-action@v1

      - name: Format, Lint, Publishability
        run: melos run lint:all
      - name: Run Tests
        run: melos run test:coverage_all

  android_examples:
    name: Build Android Examples
    needs: quality
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
      - uses: bluefireteam/melos-action@v1

      - name: Build Android Examples
        run: melos run build:android

  ios_examples:
    name: Build iOS Examples
    needs: quality
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
      - uses: bluefireteam/melos-action@v1

      - name: Build iOS Examples
        run: melos run build:ios