name: Publishing

on:
  push:
    tags:
      - apptive_grid_*-v[0-9]+.[0-9]+.[0-9]+*'

concurrency:
  group: publish-${{ github.event.commits[0].id }}

jobs:
  publish:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Make sure that VERSION_PAT is a valid PAT with Read/Write Access to the Repository's content
          # Also make sure that the Token is allowed to bypass Branch Protection Rules
          token: ${{ secrets.VERSION_PAT }}
      - uses: subosito/flutter-action@v2
      - uses: bluefireteam/melos-action@v1

      - name: Publish
        run: melos publish -y --no-dry-run